package com.wheejuni.spring.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "redirections")
public class Redirection {
	
	private String uniqueid;
	private String mappedUrl;
	private String originalUrl;
	
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getUniqueId() {
		return this.uniqueid;
	}
	
	@DynamoDBAttribute
	public String getMappedUrl() {
		return this.mappedUrl;
	}
	
	@DynamoDBAttribute
	public String getOriginalUrl() {
		return this.mappedUrl;
	}
	
	public Redirection(String mappedUrl, String originalUrl) {
		this.mappedUrl = mappedUrl;
		this.originalUrl = originalUrl;
	}
	
	public void setMappedUrl(String mappedUrl) {
		this.mappedUrl = mappedUrl;
	}
	
	public void setOriginalUrl(String originalUrl) {
		this.originalUrl = originalUrl;
	}
	
	
}
